# Generated by Django 3.2.11 on 2024-09-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookdetail_name_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('C', '童書'), ('D', '偵探小說'), ('S', '自然科學'), ('N', '文學小說'), ('F', '財經')], max_length=1),
        ),
    ]
